services:
  db:
    image: docker.io/postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_DB: swappers_online_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - swappers_online_dev_data:/var/lib/postgresql/data
volumes:
  swappers_online_dev_data:
